# Generated by Django 5.2.5 on 2025-09-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matrícula')),
                ('carrera', models.CharField(blank=True, max_length=120, verbose_name='Carrera')),
                ('role', models.CharField(choices=[('P', 'Publicante'), ('A', 'Autorizador')], default='P', max_length=1, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
