# Generated by Django 5.2.5 on 2025-09-10 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(blank=True, max_length=512, verbose_name='Resumen')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('autorizado_por', models.ForeignKey(blank=True, limit_choices_to={'role': 'A'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_publications', to='estudiantes.student', verbose_name='Autorizado por')),
                ('publisher', models.ForeignKey(limit_choices_to={'role': 'P'}, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='estudiantes.student', verbose_name='Publicado por')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-published_at'],
            },
        ),
    ]
